enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
rv-brand = "ReVanced MNML"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"                                                   
excluded-patches = "'Seekbar tapping' 'Always autorepeat' 'Enable debugging' 'Client spoof' 'Hide filter bar' 'Hide endscreen cards' 'Hide album cards' 'Hide seekbar' 'Hide cast button' 'Enable tablet layout' 'Premium heading' 'Spoof app version' 'Alternative thumbnails'"
included-patches = "'Remove player controls background'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rv-mnml"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
excluded-patches = ""
included-patches = "'Permanent repeat' 'Permanent shuffle'"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rv-mnml"
arch = "arm64-v8a"

[Twitch]
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[Photos]
version = "latest"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"
